// [EXPORT] //
module.exports = [
	// flavor //
	{
		_id: '1',
		type: 'flavor',
		title: 'Plain',
		description: '',
		image: '',
		cost: 0.00,
		hasProductAddition: false,
	},
	{
		_id: '2',
		type: 'flavor',
		title: 'Pineapple BBQ',
		description: '',
		image: '',
		cost: 0.00,
		hasProductAddition: false,
	},
	{
		_id: '3',
		type: 'flavor',
		title: 'Honey BBQ',
		description: '',
		image: '',
		cost: 0.00,
		hasProductAddition: false,
	},
	{
		_id: '4',
		type: 'flavor',
		title: 'Honey Garlic',
		description: '',
		image: '',
		cost: 0.00,
		hasProductAddition: false,
	},
	{
		_id: '5',
		type: 'flavor',
		title: 'Asian Sesame',
		description: '',
		image: '',
		cost: 0.00,
		hasProductAddition: false,
	},
	{
		_id: '6',
		type: 'flavor',
		title: 'General Tso',
		description: '',
		image: '',
		cost: 0.00,
		hasProductAddition: false,
	},
	{
		_id: '7',
		type: 'flavor',
		title: 'Mojita Lime',
		description: '',
		image: '',
		cost: 0.00,
		hasProductAddition: false,
	},
	{
		_id: '8',
		type: 'flavor',
		title: 'Buffalo Dry Rub',
		description: '',
		image: '',
		cost: 0.00,
		hasProductAddition: false,
	},
	{
		_id: '9',
		type: 'flavor',
		title: 'Buffalo Mild',
		description: '',
		image: '',
		cost: 0.00,
		hasProductAddition: false,
	},
	{
		_id: '10',
		type: 'flavor',
		title: 'Teriyaki Sauce',
		description: '',
		image: '',
		cost: 0.00,
		hasProductAddition: false,
	},
	{
		_id: '12',
		type: 'flavor',
		title: 'Lousiana Sauce',
		description: '',
		image: '',
		cost: 0.00,
		hasProductAddition: false,
	},
	{
		_id: '13',
		type: 'flavor',
		title: 'Korean BBQ',
		description: '',
		image: '',
		cost: 0.00,
		hasProductAddition: false,
	},
	{
		_id: '14',
		type: 'flavor',
		title: 'Ragin\' Cajun',
		description: '',
		image: '',
		cost: 0.00,
		hasProductAddition: false,
	},
	{
		_id: '15',
		type: 'flavor',
		title: 'Mango Habanero',
		description: '',
		image: '',
		cost: 0.00,
		hasProductAddition: false,
	},
	{
		_id: '16',
		type: 'flavor',
		title: 'Knockout',
		description: '',
		image: '',
		cost: 0.00,
		hasProductAddition: false,
	},

	// sauce //
	{
		_id: '17',
		type: 'sauce',
		title: 'Spicy Mayo',
		description: '',
		image: '',
		cost: 0.00,
		hasProductAddition: false,
	},
	{
		_id: '18',
		type: 'sauce',
		title: 'Chipotle Mayo',
		description: '',
		image: '',
		cost: 0.00,
		hasProductAddition: false,
	},
	{
		_id: '19',
		type: 'sauce',
		title: 'Teriyaki Aoli',
		description: '',
		image: '',
		cost: 0.00,
		hasProductAddition: false,
	},
	{
		_id: '20',
		type: 'sauce',
		title: 'Thousand Island',
		description: '',
		image: '',
		hasProductAddition: false,
		cost: 0.00,
	},
	{
		_id: '21',
		type: 'sauce',
		title: 'BBQ',
		description: '',
		image: '',
		cost: 0.00,
		hasProductAddition: false,
	},

	// toppings //
	{
		_id: 'patty',
		type: 'topping',
		title: 'Extra Patty',
		description: '',
		image: '',
		cost: 1.00,
		hasProductAddition: false,
	},
	{
		_id: 'sauteed-onions',
		type: 'topping',
		title: 'Sauteed Onions',
		description: '',
		image: '',
		cost: 0.50,
		hasProductAddition: false,
	},
	{
		_id: 'jalapenos',
		type: 'topping',
		title: 'Jalapenos',
		description: '',
		image: '',
		cost: 0.50,
		hasProductAddition: false,
	},
	{
		_id: 'mushrooms',
		type: 'topping',
		title: 'Mushrooms',
		description: '',
		image: '',
		cost: 0.50,
		hasProductAddition: false,
	},
	{
		_id: 'beef-bacon',
		type: 'topping',
		title: 'Beef Bacon',
		description: '',
		image: '',
		hasProductAddition: false,
		cost: 1.75,
	},
	{
		_id: 'bacon-jam',
		type: 'topping',
		title: 'Bacon Jam',
		description: '',
		image: '',
		cost: 1.75,
		hasProductAddition: false,
	},
	{
		_id: 'avacado',
		type: 'topping',
		title: 'Avacado',
		description: '',
		image: '',
		cost: 1.75,
		hasProductAddition: false,
	},
	{
		_id: 'crispy-fried-onions',
		type: 'topping',
		title: 'Crispy Fried Onions',
		description: '',
		image: '',
		cost: 0.75,
		hasProductAddition: false,
	},

	// appetizers classic //
	{
		_id: '22',
		type: 'appetizer',
		title: 'Quesadilla',
		description: '',
		image: '',
		cost: 5.99,
		hasProductAddition: false,
	},
	{
		_id: '23',
		type: 'appetizer',
		title: 'Chicken Quesadilla',
		description: '',
		image: '',
		cost: 7.49,
		hasProductAddition: false,
	},
	{
		_id: '24',
		type: 'appetizer',
		title: 'Beef Quesadilla',
		description: '',
		image: '',
		cost: 7.49,
		hasProductAddition: false,
	},
	{
		_id: '25',
		type: 'appetizer',
		title: 'Fried Mac and Cheese Bites',
		description: '',
		image: '',
		cost: 5.99,
		hasProductAddition: false,
	},
	{
		_id: '26',
		type: 'appetizer',
		title: 'Fried Cauliflower Pops',
		description: '',
		image: '',
		hasProductAddition: false,
		cost: 4.99,
	},
	{
		_id: '27',
		type: 'appetizer',
		title: 'Fried Pickles',
		description: '',
		image: '',
		hasProductAddition: false,
		cost: 5.99,
	},
	{
		_id: '28',
		type: 'appetizer',
		title: 'Mozzerella Sticks',
		description: '',
		image: '',
		hasProductAddition: false,
		cost: 4.99,
	},
	{
		_id: '29',
		type: 'appetizer',
		title: 'Onion Rings',
		description: '',
		image: '',
		cost: 2.99,
		hasProductAddition: false,
	},
]