// [EXPORT] //
module.exports = [
	// wingsAndTenders wings //
	{
		_id: 'wingsAndTenders-wings-6',
		cat: 'wingsAndTenders',
		subCat: 'wings',
		title: '6 Pieces Wings',
		image: 'https://i.imgur.com/X5gq5BN.jpg',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: 'Get 6 pieces of wings with your choice of flavor',
		cost: 6.99,
	},
	{
		_id: 'wingsAndTenders-wings-12',
		cat: 'wingsAndTenders',
		subCat: 'wings',
		title: '12 Pieces Wings',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: 'Get 12 pieces of wings with your choice of flavor',
		cost: 12.99,
	},
	{
		_id: 'wingsAndTenders-wings-24',
		cat: 'wingsAndTenders',
		subCat: 'wings',
		title: '24 Pieces Wings',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: 'Get 24 pieces of wings with your choice of flavor',
		cost: 24.99,
	},

	// wingsAndTenders tenders //
	{
		_id: 'wingsAndTenders-tenders-3',
		cat: 'wingsAndTenders',
		subCat: 'tenders',
		title: '3 Pieces Wings',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: '',
		cost: 4.99,
	},
	{
		_id: 'wingsAndTenders-tenders-6',
		cat: 'wingsAndTenders',
		subCat: 'tenders',
		title: '6 Pieces Wings',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: '',
		cost: 12.99,
	},

	// sliders sliders //
	{
		_id: 'sliders-sliders-single-slider',
		cat: 'sliders',
		subCat: 'sliders',
		title: 'Single Slider',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: '',
		cost: 2.99,
	},
	{
		_id: 'sliders-sliders-double-slider',
		cat: 'sliders',
		subCat: 'sliders',
		title: 'Double Slider',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: '',
		cost: 4.99,
	},
	{
		_id: 'sliders-sliders-triple-slider',
		cat: 'sliders',
		subCat: 'sliders',
		title: 'Triple Slider',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: '',
		cost: 6.99,
	},

	// sliders toppings //
	{
		_id: 'sliders-toppings-sauteed-onions',
		cat: 'sliders',
		subCat: 'toppings',
		title: 'Sauteed Onions',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: '',
		cost: 0.50,
	},
	{
		_id: 'sliders-toppings-jalapenos',
		cat: 'sliders',
		subCat: 'toppings',
		title: 'Jalapenos',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: '',
		cost: 0.50,
	},
	{
		_id: 'sliders-toppings-mushrooms',
		cat: 'sliders',
		subCat: 'toppings',
		title: 'Mushrooms',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: '',
		cost: 0.50,
	},
	{
		_id: 'sliders-toppings-beef-bacon',
		cat: 'sliders',
		subCat: 'toppings',
		title: 'Beef Bacon',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: '',
		cost: 1.75,
	},
	{
		_id: 'sliders-toppings-bacon-jam',
		cat: 'sliders',
		subCat: 'toppings',
		title: 'Bacon Jam',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: '',
		cost: 1.75,
	},
	{
		_id: 'sliders-toppings-avacado',
		cat: 'sliders',
		subCat: 'toppings',
		title: 'Avacado',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: '',
		cost: 1.75,
	},
	{
		_id: 'sliders-toppings-crispy-fried-onions',
		cat: 'sliders',
		subCat: 'toppings',
		title: 'Crispy Fried Onions',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: '',
		cost: 0.75,
	},

	// sliders extras //
	{
		_id: 'sliders-extras-patty',
		cat: 'sliders',
		subCat: 'extras',
		title: 'Patty',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: '',
		cost: 1.00,
	},

	// sliders additions //
	{
		_id: 'sliders-additions-art-appetizer',
		cat: 'sliders',
		subCat: 'additions',
		title: 'Art Appetizer',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: 'Add any art appetizers (except for Quesadilla, Chicken Quesadilla, & Beef Quesadilla)',
		cost: 2.99,
	},
	{
		_id: 'sliders-additions-traditional-or-boneless-4pc-wings',
		cat: 'sliders',
		subCat: 'additions',
		title: 'Traditional or Boneless 4pc Wings',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: 'Add wings (traditional or boneless) with any choice of sauce',
		cost: 4.99,
	},

	// signatureDishes burgers //
	{
		_id: 'signatureDishes-burgers-jamaican-burger',
		cat: 'signatureDishes',
		subCat: 'burgers',
		title: 'Jamaican Burger',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: '6oz burger, bacon jam, swiss cheese, signature sauce',
		cost: 8.99,
	},
	{
		_id: 'signatureDishes-burgers-bbq-burger',
		cat: 'signatureDishes',
		subCat: 'burgers',
		title: 'BBQ Burger',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: '6oz burger, BBQ sauce, cheddar, crispy onions, beef bacon, tomato',
		cost: 7.50,
	},
	{
		_id: 'signatureDishes-burgers-spicy-art-burger',
		cat: 'signatureDishes',
		subCat: 'burgers',
		title: 'Spicy Art Burger',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: 'Jalapenos, spicy mayo, cheddar cheese, beef bacon',
		cost: 7.50,
	},
	{
		_id: 'signatureDishes-burgers-chop-cheese-burger',
		cat: 'signatureDishes',
		subCat: 'burgers',
		title: 'Chop Cheese Burger',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: '6oz burger with choices of lettuce, tomato, or onions served on an italian roll',
		cost: 6.99,
	},

	// signatureDishes sandwiches //
	{
		_id: 'signatureDishes-sandwiches-grilled-cheese-sandwich',
		cat: 'signatureDishes',
		subCat: 'sandwiches',
		title: 'Grilled Cheese Sandwich',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: 'Classic grilled cheese sandwich',
		cost: 4.99,
	},
	{
		_id: 'signatureDishes-sandwiches-deluxe',
		cat: 'signatureDishes',
		subCat: 'sandwiches',
		title: 'Grilled Cheese Sandwich Deluxe',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: 'Grilled cheese sandwich with bacon, lettuce, & tomatos',
		cost: 6.99,
	},
	{
		_id: 'signatureDishes-sandwiches-classic-chicken-sandwich',
		cat: 'signatureDishes',
		subCat: 'sandwiches',
		title: 'Classic Chicken Sandwich',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: 'Crispy or grilled chicken, spicy mayo, lettuce, tomato',
		cost: 7.50,
	},
	{
		_id: 'signatureDishes-sandwiches-buffalo-chicken-sandwich',
		cat: 'signatureDishes',
		subCat: 'sandwiches',
		title: 'Buffalo Chicken Sandwich',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: 'Crispy or grilled chicken buffalo sauce, blue cheese, crispy onions',
		cost: 7.50,
	},
	{
		_id: 'signatureDishes-sandwiches-art-bbq-chicken-sandwich',
		cat: 'signatureDishes',
		subCat: 'sandwiches',
		title: 'Art BBQ Chicken Sandwich',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: 'Crispy or grilled chicken BBQ sauce, coleslaw, pickles, bacon',
		cost: 7.50,
	},

	// signatureDishes subs //
	{
		_id: 'signatureDishes-subs-the-rutgers-cheesesteak',
		cat: 'signatureDishes',
		subCat: 'subs',
		title: 'The Rutgers Cheesesteak',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: 'Grilled beef, sauteed onions, american cheese, thousand island, served on a brioche roll',
		cost: 6.99,
	},
	{
		_id: 'signatureDishes-subs-cheesesteak',
		cat: 'signatureDishes',
		subCat: 'subs',
		title: 'Cheesesteak',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: 'Melted American cheese w/sweet peppers & onions',
		cost: 6.99,
	},

	// specialtySides FrienchFriesOrTatorTots //
	{
		_id: 'specialtySides-FrienchFriesOrTatorTots-plain',
		cat: 'specialtySides',
		subCat: 'FrienchFriesOrTatorTots',
		title: 'plain',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: 'Classic side',
		cost: 2.99,
	},
	{
		_id: 'specialtySides-FrienchFriesOrTatorTots-sweet-potato',
		cat: 'specialtySides',
		subCat: 'FrienchFriesOrTatorTots',
		title: 'Sweet Potato',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: 'Sweet potato',
		cost: 3.99,
	},
	{
		_id: 'specialtySides-FrienchFriesOrTatorTots-loaded',
		cat: 'specialtySides',
		subCat: 'FrienchFriesOrTatorTots',
		title: 'Loaded',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: 'Melted cheese, sour cream, and bacon',
		cost: 5.99,
	},
	{
		_id: 'specialtySides-FrienchFriesOrTatorTots-chicken',
		cat: 'specialtySides',
		subCat: 'FrienchFriesOrTatorTots',
		title: 'Chicken',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: 'Spicy mayo, fried or grilled chicken, crispy onions',
		cost: 5.75,
	},
	{
		_id: 'specialtySides-FrienchFriesOrTatorTots-burger',
		cat: 'specialtySides',
		subCat: 'FrienchFriesOrTatorTots',
		title: 'Burger',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: 'Melted American cheese, art burger sauce, red onions',
		cost: 5.25,
	},
	{
		_id: 'specialtySides-FrienchFriesOrTatorTots-fiery',
		cat: 'specialtySides',
		subCat: 'FrienchFriesOrTatorTots',
		title: 'Fiery',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: 'Melted cheese, jalapeno, and chili',
		cost: 5.99,
	},
	{
		_id: 'specialtySides-FrienchFriesOrTatorTots-cheese',
		cat: 'specialtySides',
		subCat: 'FrienchFriesOrTatorTots',
		title: 'Cheese',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: 'Melted cheese',
		cost: 4.99,
	},
	{
		_id: 'specialtySides-FrienchFriesOrTatorTots-mac-and-cheese',
		cat: 'specialtySides',
		subCat: 'FrienchFriesOrTatorTots',
		title: 'Mac & Cheese',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: 'Mac & cheese',
		cost: 4.99,
	},
	{
		_id: 'specialtySides-FrienchFriesOrTatorTots-mac-and-cheese-with-bacon',
		cat: 'specialtySides',
		subCat: 'FrienchFriesOrTatorTots',
		title: 'Mac & Cheese w/Bacon',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: 'Mac & cheese and Bacon',
		cost: 6.49,
	},
	{
		_id: 'specialtySides-FrienchFriesOrTatorTots-funnel-fries',
		cat: 'specialtySides',
		subCat: 'FrienchFriesOrTatorTots',
		title: 'Funnel Fries',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: 'Classic Funnel fries',
		cost: 4.95,
	},

	// appetizers classic //
	{
		_id: 'appetizers-classic-quesadilla',
		cat: 'appetizers',
		subCat: 'classic',
		title: 'Quesadilla',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: '',
		cost: 5.99,
	},
	{
		_id: 'appetizers-classic-chicken-quesadilla',
		cat: 'appetizers',
		subCat: 'classic',
		title: 'Chicken Quesadilla',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: '',
		cost: 7.49,
	},
	{
		_id: 'appetizers-classic-beef-quesadilla',
		cat: 'appetizers',
		subCat: 'classic',
		title: 'Beef Quesadilla',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: '',
		cost: 7.49,
	},
	{
		_id: 'appetizers-classic-friend-mac-and-cheese-bites',
		cat: 'appetizers',
		subCat: 'classic',
		title: 'Fried Mac and Cheese Bites',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: '',
		cost: 5.99,
	},
	{
		_id: 'appetizers-classic-fried-cauliflower-pops',
		cat: 'appetizers',
		subCat: 'classic',
		title: 'Fried Cauliflower Pops',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: '',
		cost: 4.99,
	},
	{
		_id: 'appetizers-classic-fried-pickles',
		cat: 'appetizers',
		subCat: 'classic',
		title: 'Fried Pickles',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: '',
		cost: 5.99,
	},
	{
		_id: 'appetizers-classic-mozzerella-sticks',
		cat: 'appetizers',
		subCat: 'classic',
		title: 'Mozzerella Sticks',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: '',
		cost: 4.99,
	},
	{
		_id: 'appetizers-classic-onion-rings',
		cat: 'appetizers',
		subCat: 'classic',
		title: 'Onion Rings',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: '',
		cost: 2.99,
	},

	// salads classic //
	{
		_id: 'salads-classic-house-salad',
		cat: 'salads',
		subCat: 'classic',
		title: 'House Salad',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: 'Lettuce, tomato, cucumbers, and red onions.',
		cost: 4.95,
	},
	{
		_id: 'salads-classic-house-salad-with-chicken',
		cat: 'salads',
		subCat: 'classic',
		title: 'House Salad w/Chicken',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: 'Lettuce, tomato, cucumbers, red onions, and chicken.',
		cost: 6.95,
	},
	{
		_id: 'salads-classic-portobello-salad',
		cat: 'salads',
		subCat: 'classic',
		title: 'Portobello Salad',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: 'Portobellos, argula, red onions, balsamic vinegar, and tomato.',
		cost: 5.95,
	},
	{
		_id: 'salads-classic-portobello-salad-with-chicken',
		cat: 'salads',
		subCat: 'classic',
		title: 'Portobello Salad w/Chicken',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: 'Portobellos, argula, red onions, balsamic vinegar, tomato, and chicken',
		cost: 7.95,
	},

	// plantbased beyond //
	{
		_id: 'plantbased-beyond-beyond-quesadilla',
		cat: 'plantbased',
		subCat: 'beyond',
		title: 'Beyond Quesadilla',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: '',
		cost: 9.99,
	},
	{
		_id: 'plantbased-beyond-beyond-burger',
		cat: 'plantbased',
		subCat: 'beyond',
		title: 'Beyond Burger',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: '',
		cost: 9.99,
	},
	{
		_id: 'plantbased-beyond-beyond-chop-cheese-burger',
		cat: 'plantbased',
		subCat: 'beyond',
		title: 'Beyond Chop Cheese Burger',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: '',
		cost: 9.99,
	},
	
	// plantbased veggie //
	{
		_id: 'plantbased-veggie-portobello-burger',
		cat: 'plantbased',
		subCat: 'veggies',
		title: 'Portobello Burger',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: '',
		cost: 6.99,
	},
	{
		_id: 'plantbased-veggie-veggie-burger',
		cat: 'plantbased',
		subCat: 'veggie',
		title: 'Veggie Burger',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: '',
		cost: 7.99,
	},

	// beverages sodas //
	{
		_id: 'beverages-sodas-bottled-soda',
		cat: 'beverages',
		subCat: 'soda',
		title: 'Bottled Soda',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: '',
		cost: 2.69,
	},

	// Beverages notSodas //
	{
		_id: 'beverages-notSodas-bottled-water',
		cat: 'beverages',
		subCat: 'notSodas',
		title: 'Bottled Water',
		image: '',
		flavorsAvailable: false,
		saucesAvailable: false,
		toppingsAvailable: false,
		extrasAvailable: false,
		description: '',
		cost: 1.69,
	},
]