// [EXPORT] //
module.exports = [
	// wingsAndTenders wings //
	{
		cat: 'wingsAndTenders',
		subCat: 'wings',
		title: '6 Piece Wings',
		description: 'Get 6 pieces of wings with your choice of flavor',
		image: 'https://i.imgur.com/X5gq5BN.jpg',
		cost: 6.99,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},
	{
		cat: 'wingsAndTenders',
		subCat: 'wings',
		title: '12 Piece Wings',
		description: 'Get 12 pieces of wings with your choice of flavor',
		image: '',
		cost: 12.99,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},
	{
		cat: 'wingsAndTenders',
		subCat: 'wings',
		title: '24 Piece Wings',
		description: 'Get 24 pieces of wings with your choice of flavor',
		image: '',
		cost: 24.99,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},

	// wingsAndTenders tenders //
	{
		cat: 'wingsAndTenders',
		subCat: 'tenders',
		title: '3 Piece Tenders',
		description: '',
		image: '',	
		cost: 4.99,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},
	{
		cat: 'wingsAndTenders',
		subCat: 'tenders',
		title: '6 Piece Tenders',
		description: '',
		image: '',	
		cost: 12.99,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},

	// sliders sliders //
	{
		cat: 'sliders',
		subCat: 'sliders',
		title: 'Single Slider',
		description: '',
		image: '',
		cost: 2.99,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},
	{
		cat: 'sliders',
		subCat: 'sliders',
		title: 'Double Slider',
		description: '',
		image: '',
		cost: 4.99,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},
	{
		cat: 'sliders',
		subCat: 'sliders',
		title: 'Triple Slider',
		description: '',
		image: '',
		cost: 6.99,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},

	// sliders additions //
	{
		cat: 'sliders',
		subCat: 'additions',
		title: 'Art Appetizer',
		description: 'Add any art appetizers (except for Quesadilla, Chicken Quesadilla, & Beef Quesadilla)',
		image: '',
		cost: 2.99,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},
	{
		cat: 'sliders',
		subCat: 'additions',
		title: 'Traditional or Boneless wings 4pc-wings',
		description: 'With any choice of sauce',
		image: '',
		cost: 4.99,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},

	// signatureDishes burgers //
	{
		cat: 'signatureDishes',
		subCat: 'burgers',
		title: 'Jamaican Burger',
		description: '6oz burger, bacon jam, swiss cheese, signature sauce',
		image: '',
		cost: 8.99,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},
	{
		cat: 'signatureDishes',
		subCat: 'burgers',
		title: 'BBQ Burger',
		description: '6oz burger, BBQ sauce, cheddar, crispy onions, beef bacon, tomato',
		image: '',
		cost: 7.50,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},
	{
		cat: 'signatureDishes',
		subCat: 'burgers',
		title: 'Spicy Art Burger',
		description: 'Jalapenos, spicy mayo, cheddar cheese, beef bacon',
		image: '',
		cost: 7.50,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},
	{
		cat: 'signatureDishes',
		subCat: 'burgers',
		title: 'Chop Cheese Burger',
		description: '6oz burger with choices of lettuce, tomato, or onions served on an italian roll',
		image: '',
		cost: 6.99,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},

	// signatureDishes sandwiches //
	{
		cat: 'signatureDishes',
		subCat: 'sandwiches',
		title: 'Grilled Cheese Sandwich',
		description: 'Classic grilled cheese sandwich',
		image: '',
		cost: 4.99,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},
	{
		cat: 'signatureDishes',
		subCat: 'sandwiches',
		title: 'Grilled Cheese Sandwich Deluxe',
		description: 'Grilled cheese sandwich with bacon, lettuce, & tomatos',
		image: '',
		cost: 6.99,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},
	{
		cat: 'signatureDishes',
		subCat: 'sandwiches',
		title: 'Classic Chicken Sandwich',
		description: 'Crispy or grilled chicken, spicy mayo, lettuce, tomato',
		image: '',
		cost: 7.50,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},
	{
		cat: 'signatureDishes',
		subCat: 'sandwiches',
		title: 'Buffalo Chicken Sandwich',
		description: 'Crispy or grilled chicken buffalo sauce, blue cheese, crispy onions',
		image: '',
		cost: 7.50,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},
	{
		cat: 'signatureDishes',
		subCat: 'sandwiches',
		title: 'Art BBQ Chicken Sandwich',
		description: 'Crispy or grilled chicken BBQ sauce, coleslaw, pickles, bacon',
		image: '',
		cost: 7.50,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},

	// signatureDishes subs //
	{
		cat: 'signatureDishes',
		subCat: 'subs',
		title: 'The Rutgers Cheesesteak',
		description: 'Grilled beef, sauteed onions, american cheese, thousand island, served on a brioche roll',
		image: '',
		cost: 6.99,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},
	{
		cat: 'signatureDishes',
		subCat: 'subs',
		title: 'Cheesesteak',
		description: 'Melted American cheese w/sweet peppers & onions',
		image: '',
		cost: 6.99,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},

	// specialtySides FrienchFriesOrTatorTots //
	{
		cat: 'specialtySides',
		subCat: 'FrienchFriesOrTatorTots',
		title: 'plain',
		description: 'Classic side',
		image: '',
		cost: 2.99,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},
	{
		cat: 'specialtySides',
		subCat: 'FrienchFriesOrTatorTots',
		title: 'Sweet Potato',
		description: 'Sweet potato',
		image: '',
		cost: 3.99,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},
	{
		cat: 'specialtySides',
		subCat: 'FrienchFriesOrTatorTots',
		title: 'Loaded',
		description: 'Melted cheese, sour cream, and bacon',
		image: '',
		cost: 5.99,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},
	{
		cat: 'specialtySides',
		subCat: 'FrienchFriesOrTatorTots',
		title: 'Chicken',
		description: 'Spicy mayo, fried or grilled chicken, crispy onions',
		image: '',
		cost: 5.75,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},
	{
		cat: 'specialtySides',
		subCat: 'FrienchFriesOrTatorTots',
		title: 'Burger',
		description: 'Melted American cheese, art burger sauce, red onions',
		image: '',
		cost: 5.25,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},
	{
		cat: 'specialtySides',
		subCat: 'FrienchFriesOrTatorTots',
		title: 'Fiery',
		description: 'Melted cheese, jalapeno, and chili',
		image: '',
		cost: 5.99,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},
	{
		cat: 'specialtySides',
		subCat: 'FrienchFriesOrTatorTots',
		title: 'Cheese',
		description: 'Melted cheese',
		image: '',
		cost: 4.99,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},
	{
		cat: 'specialtySides',
		subCat: 'FrienchFriesOrTatorTots',
		title: 'Mac & Cheese',
		description: 'Mac & cheese',
		image: '',
		cost: 4.99,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},
	{
		cat: 'specialtySides',
		subCat: 'FrienchFriesOrTatorTots',
		title: 'Mac & Cheese w/Bacon',
		description: 'Mac & cheese and Bacon',
		image: '',
		cost: 6.49,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},
	{
		cat: 'specialtySides',
		subCat: 'FrienchFriesOrTatorTots',
		title: 'Funnel Fries',
		description: 'Classic Funnel fries',
		image: '',
		cost: 4.95,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},

	// appetizers classic //
	{
		cat: 'appetizers',
		subCat: 'classic',
		title: 'Quesadilla',
		description: '',
		image: '',	
		cost: 5.99,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},
	{
		cat: 'appetizers',
		subCat: 'classic',
		title: 'Chicken Quesadilla',
		description: '',
		image: '',	
		cost: 7.49,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},
	{
		cat: 'appetizers',
		subCat: 'classic',
		title: 'Beef Quesadilla',
		description: '',
		image: '',	
		cost: 7.49,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},
	{
		cat: 'appetizers',
		subCat: 'classic',
		title: 'Fried Mac and Cheese Bites',
		description: '',
		image: '',	
		cost: 5.99,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},
	{
		cat: 'appetizers',
		subCat: 'classic',
		title: 'Fried Cauliflower Pops',
		description: '',
		image: '',	
		cost: 4.99,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},
	{
		cat: 'appetizers',
		subCat: 'classic',
		title: 'Fried Pickles',
		description: '',
		image: '',	
		cost: 5.99,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},
	{
		cat: 'appetizers',
		subCat: 'classic',
		title: 'Mozzerella Sticks',
		description: '',
		image: '',	
		cost: 4.99,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},
	{
		cat: 'appetizers',
		subCat: 'classic',
		title: 'Onion Rings',
		description: '',
		image: '',	
		cost: 2.99,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},

	// salads classic //
	{
		cat: 'salads',
		subCat: 'classic',
		title: 'House Salad',
		description: 'Lettuce, tomato, cucumbers, and red onions.',
		image: '',
		cost: 4.95,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},
	{
		cat: 'salads',
		subCat: 'classic',
		title: 'House Salad w/Chicken',
		description: 'Lettuce, tomato, cucumbers, red onions, and chicken.',
		image: '',
		cost: 6.95,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},
	{
		cat: 'salads',
		subCat: 'classic',
		title: 'Portobello Salad',
		description: 'Portobellos, argula, red onions, balsamic vinegar, and tomato.',
		image: '',
		cost: 5.95,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},
	{
		cat: 'salads',
		subCat: 'classic',
		title: 'Portobello Salad w/Chicken',
		description: 'Portobellos, argula, red onions, balsamic vinegar, tomato, and chicken',
		image: '',
		cost: 7.95,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},

	// plantbased beyond //
	{
		cat: 'plantbased',
		subCat: 'beyond',
		title: 'Beyond Quesadilla',
		description: '',
		image: '',	
		cost: 9.99,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},
	{
		cat: 'plantbased',
		subCat: 'beyond',
		title: 'Beyond Burger',
		description: '',
		image: '',	
		cost: 9.99,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},
	{
		cat: 'plantbased',
		subCat: 'beyond',
		title: 'Beyond Chop Cheese Burger',
		description: '',
		image: '',	
		cost: 9.99,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},
	
	// plantbased veggie //
	{
		cat: 'plantbased',
		subCat: 'veggies',
		title: 'Portobello Burger',
		description: '',
		image: '',	
		cost: 6.99,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},
	{
		cat: 'plantbased',
		subCat: 'veggie',
		title: 'Veggie Burger',
		description: '',
		image: '',	
		cost: 7.99,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},

	// beverages sodas //
	{
		cat: 'beverages',
		subCat: 'soda',
		title: 'Bottled Soda',
		description: '',
		image: '',	
		cost: 2.69,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},

	// Beverages notSodas //
	{
		cat: 'beverages',
		subCat: 'notSodas',
		title: 'Bottled Water',
		description: '',
		image: '',	
		cost: 1.69,
		productVariantTypes: [],
		productExtrasTypes: [],
		productAdditionsTypes: [],
	},
]