// [EXPORT] //
module.exports = [
	// Wing Flavor //
	{
		type: 'wing-flavor',
		name: 'Plain',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		type: 'wing-flavor',
		name: 'Pineapple BBQ',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		type: 'wing-flavor',
		name: 'Honey BBQ',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		type: 'wing-flavor',
		name: 'Honey Garlic',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		type: 'wing-flavor',
		name: 'Asian Sesame',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		type: 'wing-flavor',
		name: 'General Tso',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		type: 'wing-flavor',
		name: 'Mojita Lime',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		type: 'wing-flavor',
		name: 'Buffalo Dry Rub',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		type: 'wing-flavor',
		name: 'Buffalo Mild',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		type: 'wing-flavor',
		name: 'Teriyaki Sauce',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		type: 'wing-flavor',
		name: 'Lousiana Sauce',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		type: 'wing-flavor',
		name: 'Korean BBQ',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		type: 'wing-flavor',
		name: 'Ragin\' Cajun',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		type: 'wing-flavor',
		name: 'Mango Habanero',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		type: 'wing-flavor',
		name: 'Knockout',
		description: '',
		image: '',
		cost: 0.00,
	},

	// Wing Type //
	{
		type: 'wing-type',
		name: 'Traditional',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		type: 'wing-type',
		name: 'Boneless',
		description: '',
		image: '',
		cost: 0.00,
	},

	// Slider Sauce //
	{
		type: 'slider-sauce',
		name: 'Spicy Mayo',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		type: 'slider-sauce',
		name: 'Chipotle Mayo',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		type: 'slider-sauce',
		name: 'Teriyaki Aoli',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		type: 'slider-sauce',
		name: 'Thousand Island',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		type: 'slider-sauce',
		name: 'BBQ',
		description: '',
		image: '',
		cost: 0.00,
	},

	// Slider Appetizer //
	{
		type: 'slider-appetizer',
		name: 'Fried Mac and Cheese Bites',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		type: 'slider-appetizer',
		name: 'Fried Cauliflower Pops',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		type: 'slider-appetizer',
		name: 'Fried Pickles',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		type: 'slider-appetizer',
		name: 'Mozzerella Sticks',
		description: '',
		image: '',
		cost: 0.00,
	},
	{
		type: 'slider-appetizer',
		name: 'Onion Rings',
		description: '',
		image: '',
		cost: 0.00,
	},
]