// [EXPORT] //
module.exports = [
	// wingsAndTenders wings //
	{
		cat: 'wingsAndTenders',
		subCat: 'wings',
		name: '6 Piece Wings',
		description: 'Get 6 pieces of wings with your choice of flavor',
		image: 'https://i.imgur.com/X5gq5BN.jpg',
		cost: 6.99,
		productVariants: ['wing-types', 'flavors'],
		productExtras: [],
		productAdditions: [],
	},
	{
		cat: 'wingsAndTenders',
		subCat: 'wings',
		name: '12 Piece Wings',
		description: 'Get 12 pieces of wings with your choice of flavor',
		image: 'https://i.imgur.com/X5gq5BN.jpg',
		cost: 12.99,
		productVariants: ['wing-types', 'flavors'],
		productExtras: [],
		productAdditions: [],
	},
	{
		cat: 'wingsAndTenders',
		subCat: 'wings',
		name: '24 Piece Wings',
		description: 'Get 24 pieces of wings with your choice of flavor',
		image: 'https://i.imgur.com/X5gq5BN.jpg',
		cost: 24.99,
		productVariants: ['wing-types', 'flavors'],
		productExtras: [],
		productAdditions: [],
	},

	// wingsAndTenders tenders //
	{
		cat: 'wingsAndTenders',
		subCat: 'tenders',
		name: '3 Piece Tenders',
		description: '',
		image: 'https://i.imgur.com/X5gq5BN.jpg',	
		cost: 4.99,
		productVariants: [],
		productExtras: [],
		productAdditions: [],
	},
	{
		cat: 'wingsAndTenders',
		subCat: 'tenders',
		name: '6 Piece Tenders',
		description: '',
		image: 'https://i.imgur.com/X5gq5BN.jpg',	
		cost: 12.99,
		productVariants: [],
		productExtras: [],
		productAdditions: [],
	},

	// sliders sliders //
	{
		cat: 'sliders',
		subCat: 'sliders',
		name: 'Single Slider',
		description: '',
		image: 'https://i.imgur.com/X5gq5BN.jpg',
		cost: 2.99,
		productVariants: ['sauces'],
		productExtras: ['toppings'],
		productAdditions: [
			{
				cat: 'slider',
				subCat: 'appetizers',
			},
			{
				cat: 'slider',
				subCat: 'wings'
			}
		],
	},
	{
		cat: 'sliders',
		subCat: 'sliders',
		name: 'Double Slider',
		description: '',
		image: 'https://i.imgur.com/X5gq5BN.jpg',
		cost: 4.99,
		productVariants: ['sauces'],
		productExtras: ['toppings'],
		productAdditions: [
			{
				cat: 'slider',
				subCat: 'appetizers'
			},
			{
				cat: 'slider',
				subCat: 'wings'
			}
		],
	},
	{
		cat: 'sliders',
		subCat: 'sliders',
		name: 'Triple Slider',
		description: '',
		image: 'https://i.imgur.com/X5gq5BN.jpg',
		cost: 6.99,
		productVariants: ['sauces'],
		productExtras: ['toppings'],
		productAdditions: [
			{
				cat: 'slider',
				subCat: 'appetizers',
			},
			{
				cat: 'slider',
				subCat: 'wings'
			},
		],
	},

	// signatureDishes burgers //
	{
		cat: 'signatureDishes',
		subCat: 'burgers',
		name: 'Jamaican Burger',
		description: '6oz burger, bacon jam, swiss cheese, signature sauce',
		image: 'https://i.imgur.com/X5gq5BN.jpg',
		cost: 8.99,
		productVariants: [],
		productExtras: [],
		productAdditions: [],
	},
	{
		cat: 'signatureDishes',
		subCat: 'burgers',
		name: 'BBQ Burger',
		description: '6oz burger, BBQ sauce, cheddar, crispy onions, beef bacon, tomato',
		image: 'https://i.imgur.com/X5gq5BN.jpg',
		cost: 7.50,
		productVariants: [],
		productExtras: [],
		productAdditions: [],
	},
	{
		cat: 'signatureDishes',
		subCat: 'burgers',
		name: 'Spicy Art Burger',
		description: 'Jalapenos, spicy mayo, cheddar cheese, beef bacon',
		image: 'https://i.imgur.com/X5gq5BN.jpg',
		cost: 7.50,
		productVariants: [],
		productExtras: [],
		productAdditions: [],
	},
	{
		cat: 'signatureDishes',
		subCat: 'burgers',
		name: 'Chop Cheese Burger',
		description: '6oz burger with choices of lettuce, tomato, or onions served on an italian roll',
		image: 'https://i.imgur.com/X5gq5BN.jpg',
		cost: 6.99,
		productVariants: [],
		productExtras: [],
		productAdditions: [],
	},

	// signatureDishes sandwiches //
	{
		cat: 'signatureDishes',
		subCat: 'sandwiches',
		name: 'Grilled Cheese Sandwich',
		description: 'Classic grilled cheese sandwich',
		image: 'https://i.imgur.com/X5gq5BN.jpg',
		cost: 4.99,
		productVariants: [],
		productExtras: [],
		productAdditions: [],
	},
	{
		cat: 'signatureDishes',
		subCat: 'sandwiches',
		name: 'Grilled Cheese Sandwich Deluxe',
		description: 'Grilled cheese sandwich with bacon, lettuce, & tomatos',
		image: 'https://i.imgur.com/X5gq5BN.jpg',
		cost: 6.99,
		productVariants: [],
		productExtras: [],
		productAdditions: [],
	},
	{
		cat: 'signatureDishes',
		subCat: 'sandwiches',
		name: 'Classic Chicken Sandwich',
		description: 'Crispy or grilled chicken, spicy mayo, lettuce, tomato',
		image: 'https://i.imgur.com/X5gq5BN.jpg',
		cost: 7.50,
		productVariants: [],
		productExtras: [],
		productAdditions: [],
	},
	{
		cat: 'signatureDishes',
		subCat: 'sandwiches',
		name: 'Buffalo Chicken Sandwich',
		description: 'Crispy or grilled chicken buffalo sauce, blue cheese, crispy onions',
		image: 'https://i.imgur.com/X5gq5BN.jpg',
		cost: 7.50,
		productVariants: [],
		productExtras: [],
		productAdditions: [],
	},
	{
		cat: 'signatureDishes',
		subCat: 'sandwiches',
		name: 'Art BBQ Chicken Sandwich',
		description: 'Crispy or grilled chicken BBQ sauce, coleslaw, pickles, bacon',
		image: 'https://i.imgur.com/X5gq5BN.jpg',
		cost: 7.50,
		productVariants: [],
		productExtras: [],
		productAdditions: [],
	},

	// signatureDishes subs //
	{
		cat: 'signatureDishes',
		subCat: 'subs',
		name: 'The Rutgers Cheesesteak',
		description: 'Grilled beef, sauteed onions, american cheese, thousand island, served on a brioche roll',
		image: 'https://i.imgur.com/X5gq5BN.jpg',
		cost: 6.99,
		productVariants: [],
		productExtras: [],
		productAdditions: [],
	},
	{
		cat: 'signatureDishes',
		subCat: 'subs',
		name: 'Cheesesteak',
		description: 'Melted American cheese w/sweet peppers & onions',
		image: 'https://i.imgur.com/X5gq5BN.jpg',
		cost: 6.99,
		productVariants: [],
		productExtras: [],
		productAdditions: [],
	},

	// specialtySides FrienchFriesOrTatorTots //
	{
		cat: 'specialtySides',
		subCat: 'FrienchFriesOrTatorTots',
		name: 'plain',
		description: 'Classic side',
		image: 'https://i.imgur.com/X5gq5BN.jpg',
		cost: 2.99,
		productVariants: [],
		productExtras: [],
		productAdditions: [],
	},
	{
		cat: 'specialtySides',
		subCat: 'FrienchFriesOrTatorTots',
		name: 'Sweet Potato',
		description: 'Sweet potato',
		image: 'https://i.imgur.com/X5gq5BN.jpg',
		cost: 3.99,
		productVariants: [],
		productExtras: [],
		productAdditions: [],
	},
	{
		cat: 'specialtySides',
		subCat: 'FrienchFriesOrTatorTots',
		name: 'Loaded',
		description: 'Melted cheese, sour cream, and bacon',
		image: 'https://i.imgur.com/X5gq5BN.jpg',
		cost: 5.99,
		productVariants: [],
		productExtras: [],
		productAdditions: [],
	},
	{
		cat: 'specialtySides',
		subCat: 'FrienchFriesOrTatorTots',
		name: 'Chicken',
		description: 'Spicy mayo, fried or grilled chicken, crispy onions',
		image: 'https://i.imgur.com/X5gq5BN.jpg',
		cost: 5.75,
		productVariants: [],
		productExtras: [],
		productAdditions: [],
	},
	{
		cat: 'specialtySides',
		subCat: 'FrienchFriesOrTatorTots',
		name: 'Burger',
		description: 'Melted American cheese, art burger sauce, red onions',
		image: 'https://i.imgur.com/X5gq5BN.jpg',
		cost: 5.25,
		productVariants: [],
		productExtras: [],
		productAdditions: [],
	},
	{
		cat: 'specialtySides',
		subCat: 'FrienchFriesOrTatorTots',
		name: 'Fiery',
		description: 'Melted cheese, jalapeno, and chili',
		image: 'https://i.imgur.com/X5gq5BN.jpg',
		cost: 5.99,
		productVariants: [],
		productExtras: [],
		productAdditions: [],
	},
	{
		cat: 'specialtySides',
		subCat: 'FrienchFriesOrTatorTots',
		name: 'Cheese',
		description: 'Melted cheese',
		image: 'https://i.imgur.com/X5gq5BN.jpg',
		cost: 4.99,
		productVariants: [],
		productExtras: [],
		productAdditions: [],
	},
	{
		cat: 'specialtySides',
		subCat: 'FrienchFriesOrTatorTots',
		name: 'Mac & Cheese',
		description: 'Mac & cheese',
		image: 'https://i.imgur.com/X5gq5BN.jpg',
		cost: 4.99,
		productVariants: [],
		productExtras: [],
		productAdditions: [],
	},
	{
		cat: 'specialtySides',
		subCat: 'FrienchFriesOrTatorTots',
		name: 'Mac & Cheese w/Bacon',
		description: 'Mac & cheese and Bacon',
		image: 'https://i.imgur.com/X5gq5BN.jpg',
		cost: 6.49,
		productVariants: [],
		productExtras: [],
		productAdditions: [],
	},
	{
		cat: 'specialtySides',
		subCat: 'FrienchFriesOrTatorTots',
		name: 'Funnel Fries',
		description: 'Classic Funnel fries',
		image: 'https://i.imgur.com/X5gq5BN.jpg',
		cost: 4.95,
		productVariants: [],
		productExtras: [],
		productAdditions: [],
	},

	// appetizers classic //
	{
		cat: 'appetizers',
		subCat: 'classic',
		name: 'Quesadilla',
		description: '',
		image: 'https://i.imgur.com/X5gq5BN.jpg',	
		cost: 5.99,
		productVariants: [],
		productExtras: [],
		productAdditions: [],
	},
	{
		cat: 'appetizers',
		subCat: 'classic',
		name: 'Chicken Quesadilla',
		description: '',
		image: 'https://i.imgur.com/X5gq5BN.jpg',	
		cost: 7.49,
		productVariants: [],
		productExtras: [],
		productAdditions: [],
	},
	{
		cat: 'appetizers',
		subCat: 'classic',
		name: 'Beef Quesadilla',
		description: '',
		image: 'https://i.imgur.com/X5gq5BN.jpg',	
		cost: 7.49,
		productVariants: [],
		productExtras: [],
		productAdditions: [],
	},
	{
		cat: 'appetizers',
		subCat: 'classic',
		name: 'Fried Mac and Cheese Bites',
		description: '',
		image: 'https://i.imgur.com/X5gq5BN.jpg',	
		cost: 5.99,
		productVariants: [],
		productExtras: [],
		productAdditions: [],
	},
	{
		cat: 'appetizers',
		subCat: 'classic',
		name: 'Fried Cauliflower Pops',
		description: '',
		image: 'https://i.imgur.com/X5gq5BN.jpg',	
		cost: 4.99,
		productVariants: [],
		productExtras: [],
		productAdditions: [],
	},
	{
		cat: 'appetizers',
		subCat: 'classic',
		name: 'Fried Pickles',
		description: '',
		image: 'https://i.imgur.com/X5gq5BN.jpg',	
		cost: 5.99,
		productVariants: [],
		productExtras: [],
		productAdditions: [],
	},
	{
		cat: 'appetizers',
		subCat: 'classic',
		name: 'Mozzerella Sticks',
		description: '',
		image: 'https://i.imgur.com/X5gq5BN.jpg',	
		cost: 4.99,
		productVariants: [],
		productExtras: [],
		productAdditions: [],
	},
	{
		cat: 'appetizers',
		subCat: 'classic',
		name: 'Onion Rings',
		description: '',
		image: 'https://i.imgur.com/X5gq5BN.jpg',	
		cost: 2.99,
		productVariants: [],
		productExtras: [],
		productAdditions: [],
	},

	// salads classic //
	{
		cat: 'salads',
		subCat: 'classic',
		name: 'House Salad',
		description: 'Lettuce, tomato, cucumbers, and red onions.',
		image: 'https://i.imgur.com/X5gq5BN.jpg',
		cost: 4.95,
		productVariants: [],
		productExtras: [],
		productAdditions: [],
	},
	{
		cat: 'salads',
		subCat: 'classic',
		name: 'House Salad w/Chicken',
		description: 'Lettuce, tomato, cucumbers, red onions, and chicken.',
		image: 'https://i.imgur.com/X5gq5BN.jpg',
		cost: 6.95,
		productVariants: [],
		productExtras: [],
		productAdditions: [],
	},
	{
		cat: 'salads',
		subCat: 'classic',
		name: 'Portobello Salad',
		description: 'Portobellos, argula, red onions, balsamic vinegar, and tomato.',
		image: 'https://i.imgur.com/X5gq5BN.jpg',
		cost: 5.95,
		productVariants: [],
		productExtras: [],
		productAdditions: [],
	},
	{
		cat: 'salads',
		subCat: 'classic',
		name: 'Portobello Salad w/Chicken',
		description: 'Portobellos, argula, red onions, balsamic vinegar, tomato, and chicken',
		image: 'https://i.imgur.com/X5gq5BN.jpg',
		cost: 7.95,
		productVariants: [],
		productExtras: [],
		productAdditions: [],
	},

	// plantbased beyond //
	{
		cat: 'plantbased',
		subCat: 'beyond',
		name: 'Beyond Quesadilla',
		description: '',
		image: 'https://i.imgur.com/X5gq5BN.jpg',	
		cost: 9.99,
		productVariants: [],
		productExtras: [],
		productAdditions: [],
	},
	{
		cat: 'plantbased',
		subCat: 'beyond',
		name: 'Beyond Burger',
		description: '',
		image: 'https://i.imgur.com/X5gq5BN.jpg',	
		cost: 9.99,
		productVariants: [],
		productExtras: [],
		productAdditions: [],
	},
	{
		cat: 'plantbased',
		subCat: 'beyond',
		name: 'Beyond Chop Cheese Burger',
		description: '',
		image: 'https://i.imgur.com/X5gq5BN.jpg',	
		cost: 9.99,
		productVariants: [],
		productExtras: [],
		productAdditions: [],
	},
	
	// plantbased veggie //
	{
		cat: 'plantbased',
		subCat: 'veggies',
		name: 'Portobello Burger',
		description: '',
		image: 'https://i.imgur.com/X5gq5BN.jpg',	
		cost: 6.99,
		productVariants: [],
		productExtras: [],
		productAdditions: [],
	},
	{
		cat: 'plantbased',
		subCat: 'veggie',
		name: 'Veggie Burger',
		description: '',
		image: 'https://i.imgur.com/X5gq5BN.jpg',	
		cost: 7.99,
		productVariants: [],
		productExtras: [],
		productAdditions: [],
	},

	// beverages sodas //
	{
		cat: 'beverages',
		subCat: 'soda',
		name: 'Bottled Soda',
		description: '',
		image: 'https://i.imgur.com/X5gq5BN.jpg',	
		cost: 2.69,
		productVariants: [],
		productExtras: [],
		productAdditions: [],
	},

	// Beverages notSodas //
	{
		cat: 'beverages',
		subCat: 'notSodas',
		name: 'Bottled Water',
		description: '',
		image: 'https://i.imgur.com/X5gq5BN.jpg',	
		cost: 1.69,
		productVariants: [],
		productExtras: [],
		productAdditions: [],
	},
]